name: Python Linter and Test

on:
  push:
    branches:
      - dev

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Run Python linter
      run: |
        flake8
    - name: Run pytest and pytest coverage
      run: |
        pytest --cov=app
        pytest-cov
